export enum NutrientsEnum {
  PROCNT = 'PROCNT',
  FAT = 'FAT',
  CHOCDF = 'CHOCDF',
  ENERC_KCAL = 'ENERC_KCAL',
  SUGAR = 'SUGAR',
  FIBTG = 'FIBTG',
  CA = 'CA',
  FE = 'FE',
  P = 'P',
  K = 'K',
  NA = 'NA',
  VITA_IU = 'VITA_IU',
  TOCPHA = 'TOCPHA',
  VITD = 'VITD',
  VITC = 'VITC',
  VITB12 = 'VITB12',
  FOLAC = 'FOLAC',
  CHOLE = 'CHOLE',
  FATRN = 'FATRN',
  FASAT = 'FASAT',
  FAMS = 'FAMS',
  FAPU = 'FAPU',
}
